# Generated by Django 4.2 on 2023-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default='2023-08-2', verbose_name='date'),
        ),
    ]
