# Generated by Django 4.2 on 2023-08-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('view_borrowed_books', 'View what has been borrowed'),)},
        ),
    ]
