# Generated by Django 4.2 on 2023-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default='2023-08-3', verbose_name='date'),
        ),
    ]
