# Generated by Django 4.2 on 2023-09-01 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0007_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 20, 3, 5, 110452), verbose_name='date'),
        ),
    ]
